/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form.Login_Form;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setImg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_LoginTop = new javax.swing.JPanel();
        jPanel_LoginCenter = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        fogotBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(555, 820));
        setPreferredSize(new java.awt.Dimension(555, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_LoginTop.setBackground(new java.awt.Color(153, 255, 255));
        jPanel_LoginTop.setMinimumSize(new java.awt.Dimension(555, 820));
        jPanel_LoginTop.setPreferredSize(new java.awt.Dimension(555, 820));
        jPanel_LoginTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_LoginCenter.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_LoginCenter.setPreferredSize(new java.awt.Dimension(555, 820));

        jLabel_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("Come in offical");
        jLabel_title.setPreferredSize(new java.awt.Dimension(176, 32));

        jLabel_Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Password.setText("Password");

        jLabel_UserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_UserName.setText("Username");

        userName.setBackground(new java.awt.Color(255, 255, 204));
        userName.setText("Account");
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setText("\n");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        fogotBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fogotBtn.setForeground(new java.awt.Color(153, 153, 153));
        fogotBtn.setText("Forgot Password?");
        fogotBtn.setBorder(null);
        fogotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fogotBtnActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(51, 204, 255));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");

        javax.swing.GroupLayout jPanel_LoginCenterLayout = new javax.swing.GroupLayout(jPanel_LoginCenter);
        jPanel_LoginCenter.setLayout(jPanel_LoginCenterLayout);
        jPanel_LoginCenterLayout.setHorizontalGroup(
            jPanel_LoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginCenterLayout.createSequentialGroup()
                .addGroup(jPanel_LoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LoginCenterLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel_LoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password)
                            .addComponent(userName)
                            .addComponent(fogotBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)))
                    .addGroup(jPanel_LoginCenterLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel_LoginCenterLayout.setVerticalGroup(
            jPanel_LoginCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginCenterLayout.createSequentialGroup()
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fogotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel_LoginTop.add(jPanel_LoginCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 555, 555));

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Emblem-Ubuntuone-Updating-icon.png"))); // NOI18N
        jPanel_LoginTop.add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, 140));
        picture.getAccessibleContext().setAccessibleName("\n");

        getContentPane().add(jPanel_LoginTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 555, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void fogotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fogotBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fogotBtnActionPerformed

    private ImageIcon scaleImg(JLabel jLabel, String url) {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(url));
        Image image = imageIcon.getImage();
        Image scaleImage = image.getScaledInstance(jLabel.getWidth(), jLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaleImage);

        return scaledIcon;
    }

    private void setImg() {
        String urlLogin = "/img/Emblem-Ubuntuone-Updating-icon.png";

        ImageIcon iconLogin = scaleImg(picture, urlLogin);

        picture.setIcon(iconLogin);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fogotBtn;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel_LoginCenter;
    private javax.swing.JPanel jPanel_LoginTop;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel picture;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
